version: "3.9"
    
services:
  db:
    image: mariadb:10.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: amputateroot
      MARIADB_DATABASE: go_amputator
      MARIADB_USER: goamputate
      MARIADB_PASSWORD: goamputate
    
  go-discord-amputator:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_USER: goamputate
      DB_PASSWORD: goamputate
      DB_NAME: go_amputator
      ADMINISTRATOR_IDS: ${ADMINISTRATOR_IDS}
      LOG_LEVEL: ${LOG_LEVEL}
      TOKEN: ${TOKEN}
volumes:
  db_data: {}
