name: Build and Push Docker Images with Version Tag

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: extract-tag
        run: echo "TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG_NAME}} .
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG_NAME}}
